AWSTemplateFormatVersion: '2010-09-09'
Description: Domain Generator API with WHOIS lookup and prompts storage

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: API Gateway stage name
  S3Bucket:
    Type: String
    Description: S3 bucket containing Lambda code
  S3Key:
    Type: String
    Default: function.zip
    Description: S3 key for Lambda code zip file
  GeminiApiKey:
    Type: String
    Description: Gemini API key for generating prompts
    NoEcho: true

Resources:
  # DynamoDB Table for storing example prompts
  PromptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: domain-generator-prompts
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # DynamoDB Table for caching domain availability
  DomainsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: domain-generator-domains
      AttributeDefinitions:
        - AttributeName: domain
          AttributeType: S
      KeySchema:
        - AttributeName: domain
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: domain-generator-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:DescribeTable
                Resource:
                  - !GetAtt PromptsTable.Arn
                  - !GetAtt DomainsTable.Arn

  # Lambda Function - Domain Lookup (DNS + RDAP)
  WhoisLookupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: domain-generator-whois
      Runtime: nodejs20.x
      Handler: handlers/whois.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Timeout: 15
      MemorySize: 128
      Environment:
        Variables:
          DOMAINS_TABLE: !Ref DomainsTable

  # Lambda Function - Prompts
  PromptsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: domain-generator-prompts
      Runtime: nodejs20.x
      Handler: handlers/prompts.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          PROMPTS_TABLE: !Ref PromptsTable
          GEMINI_API_KEY: !Ref GeminiApiKey

  # API Gateway REST API
  WhoisApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: domain-generator-api
      Description: Domain generator API
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resource (/whois)
  WhoisResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref WhoisApi
      ParentId: !GetAtt WhoisApi.RootResourceId
      PathPart: whois

  # API Gateway Resource (/prompts)
  PromptsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref WhoisApi
      ParentId: !GetAtt WhoisApi.RootResourceId
      PathPart: prompts

  # API Gateway Method (GET /whois)
  WhoisGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WhoisApi
      ResourceId: !Ref WhoisResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WhoisLookupFunction.Arn}/invocations

  # API Gateway Method (GET /prompts)
  PromptsGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WhoisApi
      ResourceId: !Ref PromptsResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PromptsFunction.Arn}/invocations

  # API Gateway Method (OPTIONS /whois) for CORS
  WhoisOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WhoisApi
      ResourceId: !Ref WhoisResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # API Gateway Method (OPTIONS /prompts) for CORS
  PromptsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WhoisApi
      ResourceId: !Ref PromptsResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Lambda Permission for API Gateway - WHOIS
  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WhoisLookupFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WhoisApi}/*/*/*

  # Lambda Permission for API Gateway - Prompts
  PromptsApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PromptsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WhoisApi}/*/*/*

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - WhoisGetMethod
      - WhoisOptionsMethod
      - PromptsGetMethod
      - PromptsOptionsMethod
    Properties:
      RestApiId: !Ref WhoisApi

  # API Gateway Stage
  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref WhoisApi
      DeploymentId: !Ref ApiDeployment
      StageName: !Ref StageName

Outputs:
  ApiEndpoint:
    Description: API Gateway base URL
    Value: !Sub https://${WhoisApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
    Export:
      Name: DomainGeneratorApiEndpoint

  WhoisEndpoint:
    Description: WHOIS lookup endpoint
    Value: !Sub https://${WhoisApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/whois

  PromptsEndpoint:
    Description: Prompts endpoint
    Value: !Sub https://${WhoisApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/prompts

  PromptsTableName:
    Description: DynamoDB table name for prompts
    Value: !Ref PromptsTable

  DomainsTableName:
    Description: DynamoDB table name for domain cache
    Value: !Ref DomainsTable
